@startuml EditoraConsignadoContext
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

AddRelTag("sync", $textColor="black", $lineColor="black", $lineStyle="dashed")

Person(contas, "Contas a Receber", "Usuario que gerencia os boletos de consignação.")
System(PAP, "Boletos no PAP", "Sistema no PAP para gerenciar boletos.")
System(SAP, "SAP", "ERP SAP que retorna informações para boletos.")
System_Ext(servicoFinanceiro, "Bradesco", "Serviço externo financeiro que gera o boleto.")

Rel(contas, PAP, "Gerencia Boleto", "HTTPS/JSON")
Rel(PAP, servicoFinanceiro, "Gera Boleto", "HTTPS/JSON")
Rel(PAP, SAP, "Consulta Informações", "RFC")

@enduml