@startuml EditoraConsignadoContainer
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/netmagazine.puml
' !include DEVICONS/sap.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

Person(contasReceber, "Contas a Receber", "Usuário que gerencia o boleto do consignado")
Container(webapp, "FrontEnd no PAP", "React", "FrontEnd em React da aplicação da Editora no PAP", $sprite="react")
Container(api, "API Backend", "NET Core", "API Rest para a aplicacao", $sprite="netmagazine")
Container(sap, "SAP", "SAP da Editora", "Sistema SAP que fornece informações da consignação")
ContainerDb(database, "Banco de Dados", "SQLServer", "Banco de dados da aplicação", $sprite="msql_server")
Container_Ext(sistemaFinanceiro, "Bradesco", "API do Bradesco", "Sistema financeiro externo que gera o boleto")

Rel(contasReceber, webapp, "Gerencia")
Rel(webapp, api, "Requisições HTTPS")
Rel(api, database, "Persiste", "Usa")
Rel(api, sap, "Consulta Informações", "Usa")
Rel(api, sistemaFinanceiro, "Requisições HTTPS", "Usa")

@enduml