@startuml Entidades
title Entidades dos Boletos da Editora

entity Emissor {
    *nome: string
    *cnpj: string
    *endereco: string
    *conta: Conta    
}

entity Cliente {
    +id: int
    *nome: string
    *cpf: string
    *endereco: Endereco        
    *email: string
    telefone: string
}

entity Faturamento {
    +id: int
    *data: date
    *valor: decimal
    *cliente_id: int
}

entity Boleto {
    +id: int
    *numero: string
    *valor: decimal
    *vencimento: date
    *status: Status
    *faturamento_id: int
}

entity Historico {
    +id: int
    *status: Status
    *observacao: string
    *data_inclusao: date
    *faturamento_id: int
}

entity Endereco {
    *logradouro: string
    *numero: string
    bairro: string
    *cidade: string
    *estado: string
    *cep: string
    *cliente_id: int
}

entity Conta {
    *agencia: string
    digito_agencia: string
    *numero: string
    *digito_numero: string
    *beneficiario: string
}

entity Status {
    +id: int
    *descricao: string
}

Emissor ||--|| Conta : possui >
Cliente ||--|| Endereco : mora >
Cliente ||--o{ Faturamento : realiza >
Faturamento ||--|| Boleto : gera >
Boleto ||--o{ Status : está >
Historico ||--|| Faturamento : registra >
Historico||--o{ Status : está >

@enduml