@startuml DiagramaSequencia
!theme materia-outline
title Diagrama de Sequência para Geração de Boletos
actor       ContasPagar  as conta
participant       Banco         as banco
participant       Cliente       as cliente
conta -> banco : Solicitar geração de boleto (rest API)
banco -> conta : Retorna boleto gerado (link)
conta -> cliente : Envia boleto via e-mail (SendGrid)

@enduml