@startuml ConsignadoEditora
Title: Caso de Uso Principal - Boleto do Consignado
!theme aws-orange

actor ContasReceber

rectangle "PAP Editora" as PAP {
    ContasReceber --- (Gerencia Boleto)
}

@enduml