@startuml
!theme plain
left to right direction

actor Usuario
actor Administrador

rectangle "Editora" {
    Usuario -- (Realizar Login)
    Usuario -- (Emitir Boleto)
    Usuario -- (Atualizar Perfil)
    Administrador -- (Gerenciar Usuários)
    Administrador -- (Visualizar Relatórios)
    (Gerenciar Usuários) .> (Realizar Login) : <<include>>
}

@enduml