@startuml ConsignadoEditora
Title: Diagrama de Caso de Uso Principal - Consignado Editora
!theme aws-orange
' left to right direction

actor Livreiro
actor Administrador

rectangle "Editora" {
    Livreiro -- (Requisita Consignado)
    Livreiro -- (Vende Consignado)
    ' Usuario -- (Atualizar Perfil)
    Administrador -- (Gera Boleto)
    ' Administrador -- (Visualizar Relatórios)
    ' (Gerenciar Usuários) .> (Realizar Login) : <<include>>
}

@enduml